[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  "solmate/=lib/solmate/src/",
  "@uniswap/v2-core/=lib/uniswap-v2-core/",
  "@uniswap/v2-periphery/=lib/uniswap-v2-periphery/",
  "@uniswap/v3-core/=lib/uniswap-v3-core/",
  "@uniswap/v3-periphery/=lib/uniswap-v3-periphery/",
  "@aave/protocol-v2/=lib/aave-protocol-v2/",
  "@chainlink/=lib/chainlink/contracts/",
  "@chainlink/contracts/=lib/chainlink/contracts/src/",
  "@openzeppelin-4.9.5/=lib/openzeppelin-contracts-4.9.5/",
  "@openzeppelin-4.9.5/contracts/=lib/openzeppelin-contracts-4.9.5/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts-4.9.5/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-4.9.5/contracts/",
  "@openzeppelin-upgradeable-4.9.5/=lib/openzeppelin-contracts-upgradeable-4.9.5/",
  "@openzeppelin-upgradeable-4.9.5/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.5/contracts/",
  "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable-4.9.5/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable-4.9.5/contracts/",
  "@openzeppelin-4.9.4/=lib/openzeppelin-contracts-4.9.4/",
  "@openzeppelin-4.9.4/contracts/=lib/openzeppelin-contracts-4.9.4/contracts/",
  "@openzeppelin-upgradeable-4.9.4/=lib/openzeppelin-contracts-upgradeable-4.9.4/",
  "@openzeppelin-upgradeable-4.9.4/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.4/contracts/",
  "@openzeppelin-4.9.3/=lib/openzeppelin-contracts-4.9.3/",
  "@openzeppelin-4.9.3/contracts/=lib/openzeppelin-contracts-4.9.3/contracts/",
  "@openzeppelin-upgradeable-4.9.3/=lib/openzeppelin-contracts-upgradeable-4.9.3/",
  "@openzeppelin-upgradeable-4.9.3/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.3/contracts/",
  "@openzeppelin-4.9.2/=lib/openzeppelin-contracts-4.9.2/",
  "@openzeppelin-4.9.2/contracts/=lib/openzeppelin-contracts-4.9.2/contracts/",
  "@openzeppelin-upgradeable-4.9.2/=lib/openzeppelin-contracts-upgradeable-4.9.2/",
  "@openzeppelin-upgradeable-4.9.2/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.2/contracts/",
  "@openzeppelin-4.9.1/=lib/openzeppelin-contracts-4.9.1/",
  "@openzeppelin-4.9.1/contracts/=lib/openzeppelin-contracts-4.9.1/contracts/",
  "@openzeppelin-upgradeable-4.9.1/=lib/openzeppelin-contracts-upgradeable-4.9.1/",
  "@openzeppelin-upgradeable-4.9.1/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.1/contracts/",
  "@openzeppelin-4.9.0/=lib/openzeppelin-contracts-4.9.0/",
  "@openzeppelin-4.9.0/contracts/=lib/openzeppelin-contracts-4.9.0/contracts/",
  "@openzeppelin-upgradeable-4.9.0/=lib/openzeppelin-contracts-upgradeable-4.9.0/",
  "@openzeppelin-upgradeable-4.9.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.9.0/contracts/",
  "@openzeppelin-4.8.3/=lib/openzeppelin-contracts-4.8.3/",
  "@openzeppelin-4.8.3/contracts/=lib/openzeppelin-contracts-4.8.3/contracts/",
  "@openzeppelin-upgradeable-4.8.3/=lib/openzeppelin-contracts-upgradeable-4.8.3/",
  "@openzeppelin-upgradeable-4.8.3/contracts/=lib/openzeppelin-contracts-upgradeable-4.8.3/contracts/",
  "@openzeppelin-4.7.3/=lib/openzeppelin-contracts-4.7.3/",
  "@openzeppelin-4.7.3/contracts/=lib/openzeppelin-contracts-4.7.3/contracts/",
  "@openzeppelin-upgradeable-4.7.3/=lib/openzeppelin-contracts-upgradeable-4.7.3/",
  "@openzeppelin-upgradeable-4.7.3/contracts/=lib/openzeppelin-contracts-upgradeable-4.7.3/contracts/",
  "@openzeppelin-4.6.0/=lib/openzeppelin-contracts-4.6.0/",
  "@openzeppelin-4.6.0/contracts/=lib/openzeppelin-contracts-4.6.0/contracts/",
  "@openzeppelin-upgradeable-4.6.0/=lib/openzeppelin-contracts-upgradeable-4.6.0/",
  "@openzeppelin-upgradeable-4.6.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.6.0/contracts/",
  "@openzeppelin-4.5.0/=lib/openzeppelin-contracts-4.5.0/",
  "@openzeppelin-4.5.0/contracts/=lib/openzeppelin-contracts-4.5.0/contracts/",
  "@openzeppelin-upgradeable-4.5.0/=lib/openzeppelin-contracts-upgradeable-4.5.0/",
  "@openzeppelin-upgradeable-4.5.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.5.0/contracts/",
  "@openzeppelin-4.4.2/=lib/openzeppelin-contracts-4.4.2/",
  "@openzeppelin-4.4.2/contracts/=lib/openzeppelin-contracts-4.4.2/contracts/",
  "@openzeppelin-upgradeable-4.4.2/=lib/openzeppelin-contracts-upgradeable-4.4.2/",
  "@openzeppelin-upgradeable-4.4.2/contracts/=lib/openzeppelin-contracts-upgradeable-4.4.2/contracts/",
  "@openzeppelin-4.3.3/=lib/openzeppelin-contracts-4.3.3/",
  "@openzeppelin-4.3.3/contracts/=lib/openzeppelin-contracts-4.3.3/contracts/",
  "@openzeppelin-upgradeable-4.3.3/=lib/openzeppelin-contracts-upgradeable-4.3.3/",
  "@openzeppelin-upgradeable-4.3.3/contracts/=lib/openzeppelin-contracts-upgradeable-4.3.3/contracts/",
  "@openzeppelin-4.2.0/=lib/openzeppelin-contracts-4.2.0/",
  "@openzeppelin-4.2.0/contracts/=lib/openzeppelin-contracts-4.2.0/contracts/",
  "@openzeppelin-upgradeable-4.2.0/=lib/openzeppelin-contracts-upgradeable-4.2.0/",
  "@openzeppelin-upgradeable-4.2.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.2.0/contracts/",
  "@openzeppelin-4.1.0/=lib/openzeppelin-contracts-4.1.0/",
  "@openzeppelin-4.1.0/contracts/=lib/openzeppelin-contracts-4.1.0/contracts/",
  "@openzeppelin-upgradeable-4.1.0/=lib/openzeppelin-contracts-upgradeable-4.1.0/",
  "@openzeppelin-upgradeable-4.1.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.1.0/contracts/",
  "@openzeppelin-4.0.0/=lib/openzeppelin-contracts-4.0.0/",
  "@openzeppelin-4.0.0/contracts/=lib/openzeppelin-contracts-4.0.0/contracts/",
  "@openzeppelin-upgradeable-4.0.0/=lib/openzeppelin-contracts-upgradeable-4.0.0/",
  "@openzeppelin-upgradeable-4.0.0/contracts/=lib/openzeppelin-contracts-upgradeable-4.0.0/contracts/"
]

[rpc_endpoints]